language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools

    - build-tools-28.0.3

    # The SDK version used to compile the project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Required if emulators need to be run
    - sys-img-x86-android-26
