language: android
dist: trusty

before_install:
    - yes | sdkmanager "platforms;android-28"

android:
  components:
    - tools
    - platform-tools

    # The SDK version used to compile the project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Required if emulators need to be run
    - sys-img-x86-android-26
