language: android
dist: trusty

android:
  components:
    - tools
    - platform-tools

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Required if emulators need to be run
    - sys-img-x86-android-26
